
sudo: false

language: node_js

matrix:
    fast_finish: true
    include:
        - node_js: node
          env: FOR=php
        - node_js: node
          env: FOR=jsp
        - node_js: node
          env: FOR=.net
        - node_js: node
          env: FOR=asp

  
before_install:
    - npm install grunt -g

install:    
    - npm install
    - grunt neditor --server="$FOR"
    # - sh -c "if [ '$FOR' = 'php' ]; then grunt neditor;  fi"
    #- sh -c "if [ '$FOR' = 'jsp' ]; then grunt neditor --server=jsp;  fi"
    #- sh -c "if [ '$FOR' = 'net' ]; then grunt neditor --server=.net;  fi"
    #- sh -c "if [ '$FOR' = 'asp' ]; then grunt neditor --server=asp;  fi"
    
script:
   
    - sh -c "tar -cvf "$FOR".tar --exclude=.git ../neditor"
    - sh -c "xz -z9 "$FOR".tar"

after_success:
    - sh -c "if [ '$FOR' = '.net' ]; then curl -T notadd.tar.xz http://v0.api.upyun.com/notadd/download/neditor/net-master.tar.xz -u "$UPYUN" -v;  fi"
    - sh -c "curl -T notadd.tar.xz http://v0.api.upyun.com/notadd/download/neditor/"FOR"-master.tar.xz -u "$UPYUN" -v"
   
notifications:
    webhooks:
        - https://hook.bearychat.com/=bwA22/travis/52fa443470377f35e5a3d068b8d2d5ca
        - https://hook.bearychat.com/=bwA7K/travis/3c04d191a6066d3e178ab8d93643e708
