sudo: false

language: node_js

node_js:
    - 8
        env: FOR=php
    - 8
        env: FOR=asp
    - 8
        env: FOR=.net
    - 8
        env: FOR=jsp

matrix:
    fast_finish: true
    
before_install:
    - npm install grunt -g
    # - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database notadd;' -U postgres; echo "$DB"; fi"
    # - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS notadd;'; echo "$DB"; fi"

install:    
    - npm install
    - sh -c "if [ '$FOR' = 'php' ]; then grunt neditor  fi"
    - sh -c "if [ '$FOR' = 'jsp' ]; then grunt neditor --server=jsp  fi"
    - sh -c "if [ '$FOR' = '.net' ]; then grunt neditor --server=.net  fi"
    - sh -c "if [ '$FOR' = 'asp' ]; then grunt neditor --server=asp  fi"
    
script:
    - vendor/bin/phpunit --verbose

after_success:
    - sh -c "if [ '$archive' = 'yes' ]; then curl -T notadd.tar.xz http://v0.api.upyun.com/notadd/download/notadd-master.tar.xz -u "$UPYUN" -v; fi"
    - bash <(curl -s https://codecov.io/bash) -t "$CODACY_PROJECT_TOKEN"

notifications:
    webhooks:
        - https://hook.bearychat.com/=bwA22/travis/52fa443470377f35e5a3d068b8d2d5ca
        - https://hook.bearychat.com/=bwA7K/travis/3c04d191a6066d3e178ab8d93643e708
